import { escapeHtml } from "./number-presentation.js";

const squadOptions = (squads) => squads.map((item) => `<option value="${item.id}">${escapeHtml(item.name)}</option>`).join("");
const authShell = (content) => `<main class="auth-page"><section class="auth-layout"><aside class="auth-brand-panel"><img src="./src/assets/number-ops-logo.png" alt="Number Ops"><div><p class="eyebrow">Operação conectada</p><h2>Números sob controle.<br>Equipe em sintonia.</h2><p>Uma visão segura e compartilhada da operação, agora protegida por autenticação.</p></div><ul><li><span>✓</span> Dados centralizados</li><li><span>✓</span> Acesso por perfil</li><li><span>✓</span> Histórico preservado</li></ul><small>Number Ops · ambiente protegido</small></aside><section class="auth-card">${content}</section></section></main>`;

export function renderLogin(message = "") {
  return authShell(`<div class="auth-mobile-brand"><img src="./src/assets/number-ops-logo.png" alt="Number Ops"></div><p class="eyebrow">Acesso seguro</p><h1>Bem-vindo ao Number Ops</h1><p class="auth-intro">Centralize e acompanhe a operação dos números em um só lugar.</p>${message ? `<div class="auth-message" role="alert">${escapeHtml(message)}</div>` : ""}<form data-auth-form="login"><label>E-mail<input class="input" name="email" type="email" autocomplete="email" placeholder="voce@empresa.com" required></label><label>Senha<input class="input" name="password" type="password" autocomplete="current-password" placeholder="Sua senha" required></label><button class="button button-primary auth-submit" type="submit">Entrar com segurança <span>→</span></button><button class="button button-quiet" type="button" data-auth-mode="register">Criar uma conta</button></form><p class="auth-footnote">Sua sessão permanece protegida pelo Supabase Auth.</p>`);
}

export function renderRegistration(squads = [], message = "") {
  return authShell(`<div class="auth-mobile-brand"><img src="./src/assets/number-ops-logo.png" alt="Number Ops"></div><p class="eyebrow">Novo acesso</p><h1>Criar conta</h1><p class="auth-intro">Comece com acesso User. Admin só pode ser concedido posteriormente por um administrador.</p>${message ? `<div class="auth-message" role="alert">${escapeHtml(message)}</div>` : ""}<form data-auth-form="register"><div class="auth-form-grid"><label>Nome<input class="input" name="name" autocomplete="name" placeholder="Nome completo" required></label><label>E-mail<input class="input" name="email" type="email" autocomplete="email" placeholder="voce@empresa.com" required></label><label>Senha<input class="input" name="password" type="password" minlength="8" autocomplete="new-password" placeholder="Mínimo de 8 caracteres" required></label><label>Cargo<select class="input" name="jobTitle" required><option value="">Selecione</option><option value="ANALYST">Analista</option><option value="ACCOUNT_MANAGER">Gerente de Contas</option></select></label><label class="auth-form-wide">Squad<select class="input" name="squadId"><option value="">Sem Squad</option>${squadOptions(squads)}</select></label></div><button class="button button-primary auth-submit" type="submit">Cadastrar com segurança <span>→</span></button><button class="button button-quiet" type="button" data-auth-mode="login">Voltar ao login</button></form>`);
}
