import { getUtilization, UTILIZATION_LABELS } from "../models/number.js";
import { escapeHtml, formatPhone, nameFor, statusLabels } from "./number-presentation.js";
const option = (item, selected) => `<option value="${item.id}" ${item.id === selected ? "selected" : ""}>${escapeHtml(item.name)}</option>`;
const roleLabels = { PRIMARY: "Principal", BACKUP: "Backup", SUPPORT: "Apoio" };
const utilClass = { IN_USE: "is-in-use", AVAILABLE: "is-available", UNAVAILABLE: "is-unavailable" };
const date = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";

export function renderCampaigns({ campaigns, clients, squads, responsibles = [], filters }) {
  const rows = campaigns.map((item) => `<tr><td><strong>${escapeHtml(item.name)}</strong><span class="table-secondary">${escapeHtml(item.notes || "Sem observações")}</span></td><td>${escapeHtml(nameFor(squads,item.squadId,"—"))}</td><td>${escapeHtml(nameFor(clients,item.clientId,"—"))}</td><td>${escapeHtml(nameFor(responsibles,item.responsibleId,"Não definido"))}</td><td><span class="status-badge ${item.status === "ACTIVE" ? "status-active" : "status-inactive"}">${item.status === "ACTIVE" ? "Ativa" : "Encerrada"}</span></td><td class="table-actions"><button class="button button-quiet" data-action="view" data-id="${item.id}">Detalhes</button><button class="button button-quiet" data-action="edit" data-id="${item.id}">Editar</button>${item.status === "ACTIVE" ? `<button class="button button-danger" data-action="close" data-id="${item.id}">Encerrar</button>` : `<button class="button button-quiet" data-action="reactivate" data-id="${item.id}">Reativar</button>`}<button class="button button-danger" data-action="hard-delete" data-id="${item.id}" data-master-only>Excluir definitivamente</button></td></tr>`).join("");
  return `<section class="numbers-page"><div class="page-heading"><div><p class="eyebrow">Operação</p><h2>Campanhas</h2><p>Gerencie campanhas e seus vínculos com números.</p></div><button class="button button-primary" data-action="add">+ Nova campanha</button></div><div class="list-controls"><label class="search-panel">Buscar<input class="input" data-action="search" type="search" value="${escapeHtml(filters.query)}" placeholder="Nome da campanha"></label><label class="filter-label">Status<select class="input" data-action="status"><option value="">Todas</option><option value="ACTIVE" ${filters.status === "ACTIVE" ? "selected" : ""}>Ativas</option><option value="CLOSED" ${filters.status === "CLOSED" ? "selected" : ""}>Encerradas</option></select></label></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Campanha</th><th>Squad</th><th>Cliente</th><th>Responsável</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows || '<tr><td class="empty-cell" colspan="6">Nenhuma campanha encontrada.</td></tr>'}</tbody></table></div></div></section>`;
}

const linkRow = (link, numbers, locations, allLinks) => {
  const number = numbers.find((entry) => entry.id === link.numberId);
  const location = number ? nameFor(locations, number.locationId, "—") : "—";
  const util = number ? getUtilization(number, allLinks.some((l) => l.numberId === number.id && !l.endedAt)) : "UNAVAILABLE";
  return `<tr><td><strong>${escapeHtml(number?.phone ? formatPhone(number.phone) : link.numberId)}</strong></td><td>${escapeHtml(number?.identification || "—")} · ${escapeHtml(location)}</td><td>${roleLabels[link.role] || escapeHtml(link.role)}</td><td>${number ? `<span class="status-badge status-${number.status.toLowerCase()}">${statusLabels[number.status]}</span>` : "—"}</td><td><span class="utilization ${utilClass[util]}">${UTILIZATION_LABELS[util]}</span></td><td>${date(link.startedAt)}</td><td>${link.endedAt ? date(link.endedAt) : `<button class="button button-quiet" data-action="end-link" data-number-id="${link.numberId}">Encerrar</button>`}</td></tr>`;
};

export function renderCampaignDetail({ item, clients, squads, responsibles = [], numbers, locations = [], links, allLinks = links }) {
  const current = links.filter((link) => !link.endedAt);
  const history = links.filter((link) => link.endedAt);
  const table = (rows, emptyText) => `<div class="table-scroll"><table><thead><tr><th>Número</th><th>Identificação/Localização</th><th>Função</th><th>Status operacional</th><th>Utilização</th><th>Início</th><th>Saída</th></tr></thead><tbody>${rows || `<tr><td class="empty-cell" colspan="7">${emptyText}</td></tr>`}</tbody></table></div>`;
  return `<section class="directory-detail"><button class="back-link" data-action="back">← Voltar para Campanhas</button><header class="directory-detail-hero"><span class="directory-icon" aria-hidden="true">◆</span><div><p class="eyebrow">Campanha</p><h2>${escapeHtml(item.name)}</h2><p>${escapeHtml(nameFor(clients,item.clientId,"Cliente não definido"))} · ${escapeHtml(nameFor(squads,item.squadId,"Squad não definido"))} · Responsável: ${escapeHtml(nameFor(responsibles,item.responsibleId,"Não definido"))}</p></div><span class="status-badge ${item.status === "ACTIVE" ? "status-active" : "status-inactive"}">${item.status === "ACTIVE" ? "Ativa" : "Encerrada"}</span></header><div class="form-actions" style="justify-content:flex-end;margin:-4px 0 18px">${item.status === "ACTIVE" ? `<button class="button button-quiet" data-action="add-links" data-id="${item.id}">+ Vincular números</button><button class="button button-danger" data-action="close" data-id="${item.id}">Encerrar campanha</button>` : `<button class="button button-primary" data-action="reactivate" data-id="${item.id}">Reativar campanha</button>`}<button class="button button-danger" data-action="hard-delete" data-id="${item.id}" data-master-only>Excluir definitivamente</button></div><section class="related-numbers-section"><div class="section-heading"><div><p class="eyebrow">Período</p><h3>${date(item.startedAt || item.createdAt)} → ${item.endedAt ? date(item.endedAt) : "em andamento"}</h3></div><span>${current.length} atual${current.length === 1 ? "" : "is"} · ${links.length} no total</span></div><h4 class="campaign-subheading">Números atuais</h4>${table(current.map((link) => linkRow(link, numbers, locations, allLinks)).join(""), "Nenhum número vinculado no momento.")}<h4 class="campaign-subheading">Histórico de números</h4>${table(history.map((link) => linkRow(link, numbers, locations, allLinks)).join(""), "Nenhum vínculo encerrado.")}</section></section>`;
}

export function renderCampaignForm({ item = {}, clients, squads, responsibles = [] }) { return `<div class="modal-backdrop"><form id="campaign-form" class="modal-card" data-id="${item.id || ""}"><div class="modal-header"><div><p class="eyebrow">Campanhas</p><h2>${item.id ? "Editar" : "Nova"} campanha</h2></div><button class="icon-button" type="button" data-action="close-form">×</button></div><div class="number-form"><label>Nome<input class="input" name="name" required value="${escapeHtml(item.name || "")}"></label><label>Cliente<select class="input" name="clientId" required><option value="">Selecione</option>${clients.map(i=>`<option value="${i.id}" ${i.id===item.clientId?"selected":""} data-squad="${i.squadId||""}">${escapeHtml(i.name)}${i.squadId?"":" · Sem Squad"}</option>`).join("")}</select></label><label>Squad<select class="input" name="squadId" required><option value="">Selecione</option>${squads.map(i=>option(i,item.squadId)).join("")}</select><small class="form-hint" data-squad-hint>O Squad é definido pelo Cliente selecionado.</small></label><label>Responsável<select class="input" name="responsibleId" required><option value="">Selecione</option>${responsibles.map(i=>option(i,item.responsibleId)).join("")}</select></label><label class="form-full">Observações<textarea class="input" name="notes" rows="3">${escapeHtml(item.notes || "")}</textarea></label><div class="form-actions"><button class="button button-quiet" type="button" data-action="close-form">Cancelar</button><button class="button button-primary" type="submit">Salvar</button></div></div></form></div>`; }

export function renderCampaignLinkAddForm({ campaign, numbers }) {
  const options = numbers.map((number) => `<option value="${number.id}">${formatPhone(number.phone)}${number.identification ? ` · ${escapeHtml(number.identification)}` : ""}</option>`).join("");
  return `<div class="modal-backdrop"><form id="campaign-add-links-form" class="modal-card" data-id="${campaign.id}"><div class="modal-header"><div><p class="eyebrow">Campanhas</p><h2>Vincular números</h2><p>${escapeHtml(campaign.name)}</p></div><button class="icon-button" type="button" data-action="close-form" aria-label="Fechar">×</button></div><div class="number-form"><label class="form-full">Números (selecione um ou vários)<select class="input" name="numberIds" multiple size="8" required>${options || '<option disabled>Nenhum número disponível</option>'}</select></label><label>Papel<select class="input" name="role" required><option value="PRIMARY">Principal</option><option value="BACKUP">Backup</option><option value="SUPPORT">Apoio</option></select></label><div class="form-actions"><button class="button button-quiet" type="button" data-action="close-form">Cancelar</button><button class="button button-primary" type="submit">Vincular</button></div></div></form></div>`;
}
