import { escapeHtml, nameFor } from "./number-presentation.js";
const option = (item, selected) => `<option value="${item.id}" ${item.id === selected ? "selected" : ""}>${escapeHtml(item.name)}</option>`;
export function renderCampaigns({ campaigns, clients, squads, filters }) {
  const rows = campaigns.map((item) => `<tr><td><strong>${escapeHtml(item.name)}</strong><span class="table-secondary">${escapeHtml(item.notes || "Sem observações")}</span></td><td>${escapeHtml(nameFor(squads,item.squadId,"—"))}</td><td>${escapeHtml(nameFor(clients,item.clientId,"—"))}</td><td><span class="status-badge ${item.status === "ACTIVE" ? "status-active" : "status-inactive"}">${item.status === "ACTIVE" ? "Ativa" : "Encerrada"}</span></td><td class="table-actions"><button class="button button-quiet" data-action="view" data-id="${item.id}">Detalhes</button><button class="button button-quiet" data-action="edit" data-id="${item.id}">Editar</button>${item.status === "ACTIVE" ? `<button class="button button-danger" data-action="close" data-id="${item.id}">Encerrar</button>` : ""}</td></tr>`).join("");
  return `<section class="numbers-page"><div class="page-heading"><div><p class="eyebrow">Operação</p><h2>Campanhas</h2><p>Gerencie campanhas e seus vínculos com números.</p></div><button class="button button-primary" data-action="add">+ Nova campanha</button></div><div class="list-controls"><label class="search-panel">Buscar<input class="input" data-action="search" type="search" value="${escapeHtml(filters.query)}" placeholder="Nome da campanha"></label><label class="filter-label">Status<select class="input" data-action="status"><option value="">Todas</option><option value="ACTIVE" ${filters.status === "ACTIVE" ? "selected" : ""}>Ativas</option><option value="CLOSED" ${filters.status === "CLOSED" ? "selected" : ""}>Encerradas</option></select></label></div><div class="table-card"><div class="table-scroll"><table><thead><tr><th>Campanha</th><th>Squad</th><th>Cliente</th><th>Status</th><th>Ações</th></tr></thead><tbody>${rows || '<tr><td class="empty-cell" colspan="5">Nenhuma campanha encontrada.</td></tr>'}</tbody></table></div></div></section>`;
}
export function renderCampaignDetail({ item, clients, squads, numbers, links }) {
  const date = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
  const role = { PRIMARY: "Principal", BACKUP: "Backup", SUPPORT: "Apoio" };
  const rows = links.map((link) => { const number = numbers.find((entry) => entry.id === link.numberId); return `<tr><td><strong>${escapeHtml(number?.phone || link.numberId)}</strong></td><td>${role[link.role] || escapeHtml(link.role)}</td><td>${date(link.startedAt)}</td><td>${link.endedAt ? date(link.endedAt) : "Atual"}</td></tr>`; }).join("");
  return `<section class="directory-detail"><button class="back-link" data-action="back">← Voltar para Campanhas</button><header class="directory-detail-hero"><span class="directory-icon" aria-hidden="true">◆</span><div><p class="eyebrow">Campanha</p><h2>${escapeHtml(item.name)}</h2><p>${escapeHtml(nameFor(clients,item.clientId,"Cliente não definido"))} · ${escapeHtml(nameFor(squads,item.squadId,"Squad não definido"))}</p></div><span class="status-badge ${item.status === "ACTIVE" ? "status-active" : "status-inactive"}">${item.status === "ACTIVE" ? "Ativa" : "Encerrada"}</span></header><section class="related-numbers-section"><div class="section-heading"><div><p class="eyebrow">Período</p><h3>${date(item.startedAt || item.createdAt)} → ${item.endedAt ? date(item.endedAt) : "em andamento"}</h3></div><span>${links.length}</span></div><div class="table-scroll"><table><thead><tr><th>Número</th><th>Papel</th><th>Entrada</th><th>Saída</th></tr></thead><tbody>${rows || '<tr><td class="empty-cell" colspan="4">Nenhum vínculo registrado.</td></tr>'}</tbody></table></div></section></section>`;
}
export function renderCampaignForm({ item = {}, clients, squads }) { return `<div class="modal-backdrop"><form id="campaign-form" class="modal-card" data-id="${item.id || ""}"><div class="modal-header"><div><p class="eyebrow">Campanhas</p><h2>${item.id ? "Editar" : "Nova"} campanha</h2></div><button class="icon-button" type="button" data-action="close-form">×</button></div><div class="number-form"><label>Nome<input class="input" name="name" required value="${escapeHtml(item.name || "")}"></label><label>Squad<select class="input" name="squadId" required><option value="">Selecione</option>${squads.map(i=>option(i,item.squadId)).join("")}</select></label><label>Cliente<select class="input" name="clientId" required><option value="">Selecione</option>${clients.map(i=>option(i,item.clientId)).join("")}</select></label><label class="form-full">Observações<textarea class="input" name="notes" rows="3">${escapeHtml(item.notes || "")}</textarea></label><div class="form-actions"><button class="button button-quiet" type="button" data-action="close-form">Cancelar</button><button class="button button-primary">Salvar</button></div></div></form></div>`; }
