import { escapeHtml, formatPhone, nameFor, statusLabels } from "./number-presentation.js";

const labels = { clients: "Clientes", groups: "Squads", responsibles: "Colaboradores" };
const singular = { clients: "Cliente", groups: "Squad", responsibles: "Colaborador" };
const icon = { clients: "◉", groups: "◇", responsibles: "♙" };
const status = (number) => `<span class="status-badge status-${number.status.toLowerCase()}">${statusLabels[number.status]}</span>`;
const date = (value) => value ? new Date(value).toLocaleDateString("pt-BR") : "—";
const directorySubtitle=(type,item,groups)=>type==="responsibles"?escapeHtml(item.team||"Sem equipe / squad"):type==="clients"?`Squad: ${escapeHtml(nameFor(groups,item.squadId,"Sem Squad"))}`:item.isActive?"Registro disponível para associação":"Registro arquivado";
const campaignCards = (campaigns, groups, links, active) => {
  const filtered = campaigns.filter((campaign) => (campaign.status === "ACTIVE") === active);
  return filtered.map((campaign) => {
    const linkedNumbers = new Set(links.filter((link) => link.campaignId === campaign.id && (!active || !link.endedAt)).map((link) => link.numberId)).size;
    return `<article class="client-campaign-card"><div><span class="status-badge ${active ? "status-active" : "status-inactive"}">${active ? "Ativa" : "Encerrada"}</span><h4>${escapeHtml(campaign.name)}</h4><p>Squad: <strong>${escapeHtml(nameFor(groups, campaign.squadId))}</strong></p><small>Início: ${date(campaign.startedAt || campaign.createdAt)}${active ? ` · ${linkedNumbers} número${linkedNumbers === 1 ? "" : "s"} vinculado${linkedNumbers === 1 ? "" : "s"}` : ` · Encerramento: ${date(campaign.endedAt)}`}</small></div><div class="client-campaign-actions"><button class="button button-quiet" data-action="open-campaign" data-id="${campaign.id}">Ver em Campanhas</button>${active ? `<button class="button button-danger" data-action="close-campaign" data-id="${campaign.id}">Finalizar campanha</button>` : ""}</div></article>`;
  }).join("") || `<div class="directory-empty compact"><span aria-hidden="true">◇</span><div><h3>Nenhuma campanha ${active ? "atual" : "anterior"}</h3><p>${active ? "Campanhas ativas deste cliente aparecerão aqui." : "Campanhas encerradas permanecerão disponíveis aqui."}</p></div></div>`;
};

export function renderDirectory(type, items, query = "", groups = []) {
  const label = labels[type];
  const queryValue = escapeHtml(query);
  const visible = items.filter((item) => item.name.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  return `<section class="directory-polished">
    <header class="directory-heading"><div><p class="eyebrow">Cadastros operacionais</p><h2>${label}</h2><p>${type === "responsibles" ? "Mantenha responsáveis e squads atualizados para a operação." : `Organize os ${label.toLocaleLowerCase("pt-BR")} ligados aos números.`}</p></div><button class="button button-primary" data-action="add">+ Adicionar ${singular[type].toLocaleLowerCase("pt-BR")}</button></header>
    <div class="directory-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><span class="sr-only">Buscar ${label.toLocaleLowerCase("pt-BR")}</span><input class="input" type="search" data-action="search" value="${queryValue}" placeholder="Buscar ${label.toLocaleLowerCase("pt-BR")}"></label><span class="directory-count">${visible.length} ${visible.length === 1 ? "registro" : "registros"}</span></div>
    <div class="directory-list">${visible.map((item) => `<article class="directory-record ${item.isActive ? "" : "is-archived"}"><span class="directory-icon" aria-hidden="true">${icon[type]}</span><div class="directory-record-main"><strong>${escapeHtml(item.name)}</strong><small>${directorySubtitle(type,item,groups)}</small></div><span class="directory-state ${item.isActive ? "is-active" : "is-archived"}">${item.isActive ? "Ativo" : "Arquivado"}</span><div class="directory-actions">${type !== "responsibles" ? `<button class="button button-quiet" data-action="view" data-id="${item.id}">Ver números</button>` : ""}<button class="button button-quiet" data-action="edit" data-id="${item.id}">Editar</button>${item.isActive ? `<button class="button button-danger" data-action="archive" data-id="${item.id}">Arquivar</button>` : `<button class="button button-primary" data-action="restore" data-id="${item.id}">Restaurar</button>`}</div></article>`).join("") || `<div class="directory-empty"><span aria-hidden="true">${icon[type]}</span><div><h3>Nenhum ${singular[type].toLocaleLowerCase("pt-BR")} encontrado</h3><p>${query ? "Tente ajustar a busca." : "Adicione o primeiro registro para começar."}</p></div>${query ? `<button class="button button-quiet" data-action="clear-search">Limpar busca</button>` : `<button class="button button-primary" data-action="add">Adicionar</button>`}</div>`}</div>
  </section>`;
}

export function renderDirectoryDetail(type, item, numbers, locations, responsibles, campaigns = [], groups = [], campaignLinks = []) {
  const label = singular[type];
  const numberRows = numbers.map((number) => `<button class="related-number" data-action="open-number" data-id="${number.id}"><div><strong>${formatPhone(number.phone)}</strong><small>${escapeHtml(number.identification || "Sem identificação")}</small></div><div class="related-number-meta">${status(number)}<small>${escapeHtml(nameFor(locations, number.locationId))} · ${escapeHtml(nameFor(responsibles, number.responsibleId))}</small></div></button>`).join("");
  const clientCampaigns = type === "clients" ? `<section class="related-numbers-section client-campaigns-section"><div class="section-heading"><div><p class="eyebrow">Campanhas</p><h3>Campanhas atuais</h3></div><span>${campaigns.filter((campaign) => campaign.status === "ACTIVE").length}</span></div><div class="client-campaign-list">${campaignCards(campaigns, groups, campaignLinks, true)}</div></section><section class="related-numbers-section client-campaigns-section"><div class="section-heading"><div><p class="eyebrow">Histórico</p><h3>Campanhas anteriores</h3></div><span>${campaigns.filter((campaign) => campaign.status !== "ACTIVE").length}</span></div><div class="client-campaign-list">${campaignCards(campaigns, groups, campaignLinks, false)}</div></section>` : "";
  return `<section class="directory-detail"><button class="back-link" data-action="back">← Voltar para ${labels[type]}</button><header class="directory-detail-hero"><span class="directory-icon" aria-hidden="true">${icon[type]}</span><div><p class="eyebrow">${label}</p><h2>${escapeHtml(item.name)}</h2><p>${directorySubtitle(type,item,groups)}</p></div><span class="directory-state ${item.isActive ? "is-active" : "is-archived"}">${item.isActive ? "Ativo" : "Arquivado"}</span></header>${clientCampaigns}<section class="related-numbers-section"><div class="section-heading"><div><p class="eyebrow">Relacionamentos</p><h3>Números associados</h3></div><span>${numbers.length}</span></div>${numberRows || `<div class="directory-empty compact"><span aria-hidden="true">#</span><div><h3>Sem números associados</h3><p>As associações aparecerão aqui quando existirem.</p></div></div>`}</section></section>`;
}

export function renderDirectoryForm(type, item = {}, groups = []) {
  const label = singular[type];
  return `<div class="modal-backdrop" role="presentation"><form id="directory-form" class="modal-card directory-form" data-id="${item.id || ""}"><div class="modal-header"><div><p class="eyebrow">Cadastro operacional</p><h2>${item.id ? "Editar" : "Adicionar"} ${label.toLocaleLowerCase("pt-BR")}</h2></div><button type="button" class="icon-button" data-action="close-form" aria-label="Fechar formulário">×</button></div><label>Nome<input class="input" name="name" required value="${escapeHtml(item.name || "")}" autocomplete="off"></label>${type === "responsibles" ? `<label>Equipe / squad<input class="input" name="team" value="${escapeHtml(item.team || "")}" autocomplete="off"></label>` : type==="clients"?`<label>Squad<select class="input" name="squadId"><option value="">Sem Squad</option>${groups.map((group)=>`<option value="${group.id}" ${group.id===item.squadId?"selected":""}>${escapeHtml(group.name)}</option>`).join("")}</select></label>`:""}<div class="form-actions"><button type="button" class="button button-quiet" data-action="close-form">Cancelar</button><button class="button button-primary">Salvar ${label.toLocaleLowerCase("pt-BR")}</button></div></form></div>`;
}
