import { escapeHtml, formatPhone, nameFor, statusLabels } from "./number-presentation.js";

const labels = { clients: "Clientes", groups: "Grupos", responsibles: "Colaboradores" };
const singular = { clients: "Cliente", groups: "Grupo", responsibles: "Colaborador" };
const icon = { clients: "◉", groups: "◇", responsibles: "♙" };
const status = (number) => `<span class="status-badge status-${number.status.toLowerCase()}">${statusLabels[number.status]}</span>`;

export function renderDirectory(type, items, query = "") {
  const label = labels[type];
  const queryValue = escapeHtml(query);
  const visible = items.filter((item) => item.name.toLocaleLowerCase("pt-BR").includes(query.toLocaleLowerCase("pt-BR")));
  return `<section class="directory-polished">
    <header class="directory-heading"><div><p class="eyebrow">Cadastros operacionais</p><h2>${label}</h2><p>${type === "responsibles" ? "Mantenha responsáveis e squads atualizados para a operação." : `Organize os ${label.toLocaleLowerCase("pt-BR")} ligados aos números.`}</p></div><button class="button button-primary" data-action="add">+ Adicionar ${singular[type].toLocaleLowerCase("pt-BR")}</button></header>
    <div class="directory-toolbar"><label class="search-field"><span aria-hidden="true">⌕</span><span class="sr-only">Buscar ${label.toLocaleLowerCase("pt-BR")}</span><input class="input" type="search" data-action="search" value="${queryValue}" placeholder="Buscar ${label.toLocaleLowerCase("pt-BR")}"></label><span class="directory-count">${visible.length} ${visible.length === 1 ? "registro" : "registros"}</span></div>
    <div class="directory-list">${visible.map((item) => `<article class="directory-record ${item.isActive ? "" : "is-archived"}"><span class="directory-icon" aria-hidden="true">${icon[type]}</span><div class="directory-record-main"><strong>${escapeHtml(item.name)}</strong>${type === "responsibles" ? `<small>${escapeHtml(item.team || "Sem equipe / squad")}</small>` : `<small>${item.isActive ? "Registro disponível para associação" : "Registro arquivado"}</small>`}</div><span class="directory-state ${item.isActive ? "is-active" : "is-archived"}">${item.isActive ? "Ativo" : "Arquivado"}</span><div class="directory-actions">${type !== "responsibles" ? `<button class="button button-quiet" data-action="view" data-id="${item.id}">Ver números</button>` : ""}<button class="button button-quiet" data-action="edit" data-id="${item.id}">Editar</button>${item.isActive ? `<button class="button button-danger" data-action="archive" data-id="${item.id}">Arquivar</button>` : `<button class="button button-primary" data-action="restore" data-id="${item.id}">Restaurar</button>`}</div></article>`).join("") || `<div class="directory-empty"><span aria-hidden="true">${icon[type]}</span><div><h3>Nenhum ${singular[type].toLocaleLowerCase("pt-BR")} encontrado</h3><p>${query ? "Tente ajustar a busca." : "Adicione o primeiro registro para começar."}</p></div>${query ? `<button class="button button-quiet" data-action="clear-search">Limpar busca</button>` : `<button class="button button-primary" data-action="add">Adicionar</button>`}</div>`}</div>
  </section>`;
}

export function renderDirectoryDetail(type, item, numbers, locations, responsibles) {
  const label = singular[type];
  const numberRows = numbers.map((number) => `<button class="related-number" data-action="open-number" data-id="${number.id}"><div><strong>${formatPhone(number.phone)}</strong><small>${escapeHtml(number.identification || "Sem identificação")}</small></div><div class="related-number-meta">${status(number)}<small>${escapeHtml(nameFor(locations, number.locationId))} · ${escapeHtml(nameFor(responsibles, number.responsibleId))}</small></div></button>`).join("");
  return `<section class="directory-detail"><button class="back-link" data-action="back">← Voltar para ${labels[type]}</button><header class="directory-detail-hero"><span class="directory-icon" aria-hidden="true">${icon[type]}</span><div><p class="eyebrow">${label}</p><h2>${escapeHtml(item.name)}</h2><p>${type === "responsibles" ? escapeHtml(item.team || "Sem equipe / squad") : item.isActive ? "Registro ativo" : "Registro arquivado"}</p></div><span class="directory-state ${item.isActive ? "is-active" : "is-archived"}">${item.isActive ? "Ativo" : "Arquivado"}</span></header><section class="related-numbers-section"><div class="section-heading"><div><p class="eyebrow">Relacionamentos</p><h3>Números associados</h3></div><span>${numbers.length}</span></div>${numberRows || `<div class="directory-empty compact"><span aria-hidden="true">#</span><div><h3>Sem números associados</h3><p>As associações aparecerão aqui quando existirem.</p></div></div>`}</section></section>`;
}

export function renderDirectoryForm(type, item = {}) {
  const label = singular[type];
  return `<div class="modal-backdrop" role="presentation"><form id="directory-form" class="modal-card directory-form" data-id="${item.id || ""}"><div class="modal-header"><div><p class="eyebrow">Cadastro operacional</p><h2>${item.id ? "Editar" : "Adicionar"} ${label.toLocaleLowerCase("pt-BR")}</h2></div><button type="button" class="icon-button" data-action="close-form" aria-label="Fechar formulário">×</button></div><label>Nome<input class="input" name="name" required value="${escapeHtml(item.name || "")}" autocomplete="off"></label>${type === "responsibles" ? `<label>Equipe / squad<input class="input" name="team" value="${escapeHtml(item.team || "")}" autocomplete="off"></label>` : ""}<div class="form-actions"><button type="button" class="button button-quiet" data-action="close-form">Cancelar</button><button class="button button-primary">Salvar ${label.toLocaleLowerCase("pt-BR")}</button></div></form></div>`;
}
