export const APP_STORAGE_KEY = "number-ops:state";
export const SCHEMA_VERSION = 2;
export const NUMBER_STATUSES = Object.freeze({ ACTIVE: "ACTIVE", WARMING: "WARMING", UNDER_REVIEW: "UNDER_REVIEW", BLOCKED: "BLOCKED", INACTIVE: "INACTIVE" });
export const INCIDENT_STATUSES = Object.freeze({ OPEN: "OPEN", RESOLVED: "RESOLVED" });
export const INCIDENT_TYPES = Object.freeze({ RESTRICTION: "RESTRICTION", FALL: "FALL", BLOCK: "BLOCK", CHIP_ISSUE: "CHIP_ISSUE", DEVICE_ISSUE: "DEVICE_ISSUE", OTHER: "OTHER" });
